### ISSUE TITLE
Could you please share the dataset?

### ISSUE THREAD

**Issue by xxxxxxxxy** [di-dimitrov/harmeme#1]
When reading your paper, I found that I could access the data in this repository. I also have some interest in meme analysis.  Actually, I took part in the Hateful Meme Detection Competition, held by Facebook. As I remembered, we cannot use the competition dataset to do further research.  I am always searching for the related dataset. Could you please share this with me? Thanks very much.

**Comment by di-dimitrov** [comment]
Hello,
Thank you for reaching out to me!
I am sorry that the instructions in the README are not clear! The dataset
is available in the repository *https://github.com/di-dimitrov/mmf
<https://github.com/di-dimitrov/mmf>*
under the following paths:
/data/datasets/memes/defaults/annotations (*labels*)
/data/datasets/memes/defaults/images (*memes*)
/data/datasets/memes_tgt/defaults/annotations (*target labels*) *`dataset
folder is same as the other task`*

I have already updated the README accordingly.

Best,
Dimitar Dimitrov
